### PR TITLE
use /etc/os-release to detect system type

### PR DESCRIPTION
**Pull request by mattf**

### CODE REVIEW

**Comment by mattf** [comment]
Ubuntu 20.04
```
$ ./data-science-stack setup-system
...
$ reboot
$ ./data-science-stack diagnostics
###NV### Thu Feb 11 11:36:50 UTC 2021 #### START Diagnostics
###NV### Thu Feb 11 11:36:50 UTC 2021 #### Run as: ubuntu
###NV### Thu Feb 11 11:36:50 UTC 2021 #### WSL: false
###NV### Thu Feb 11 11:36:50 UTC 2021 #### OS Flavor: ubuntu
###NV### Thu Feb 11 11:36:50 UTC 2021 #### OS Release: 20.04
###NV### Thu Feb 11 11:36:50 UTC 2021 #### lsb_release:
Description:	Ubuntu 20.04.2 LTS
Release:	20.04
###NV### Thu Feb 11 11:36:50 UTC 2021 #### uname -a
Linux ip-172-31-34-183 5.4.0-1037-aws #39-Ubuntu SMP Thu Jan 14 02:56:06 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
###NV### Thu Feb 11 11:36:50 UTC 2021 #### Storage (non-tmpfs, non-loopback)
Filesystem      Size  Used Avail Use% Mounted on
/dev/root        62G  3.9G   59G   7% /
###NV### Thu Feb 11 11:36:50 UTC 2021 #### Network test
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=110 time=1.68 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.679/1.679/1.679/0.000 ms
###NV### Thu Feb 11 11:36:50 UTC 2021 #### Driver detected (0 means not installed): 460.39
###NV### Thu Feb 11 11:36:50 UTC 2021 #### NVIDIA SMI:
Thu Feb 11 11:36:50 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   33C    P0    25W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
###NV### Thu Feb 11 11:36:51 UTC 2021 #### CUDA detected (0 means not installed): 0
###NV### Thu Feb 11 11:36:51 UTC 2021 #### Docker detected (0 means not installed): 0
###NV### Thu Feb 11 11:36:51 UTC 2021 #### Shared libraries:
	libnvoptix.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvoptix.so.1
	libnvidia-tls.so.460.39 (libc6,x86-64, OS ABI: Linux 2.3.99) => /lib/x86_64-linux-gnu/libnvidia-tls.so.460.39
	libnvidia-rtcore.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-rtcore.so.460.39
	libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
	libnvidia-ptxjitcompiler.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so
	libnvidia-opticalflow.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1
	libnvidia-opticalflow.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-opticalflow.so
	libnvidia-opencl.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-opencl.so.1
	libnvidia-ngx.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ngx.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ml.so
	libnvidia-ifr.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ifr.so.1
	libnvidia-ifr.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-ifr.so
	libnvidia-gtk3.so.440.82 (libc6,x86-64) => /lib/libnvidia-gtk3.so.440.82
	libnvidia-gtk2.so.440.82 (libc6,x86-64) => /lib/libnvidia-gtk2.so.440.82
	libnvidia-glvkspirv.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.460.39
	libnvidia-glsi.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-glsi.so.460.39
	libnvidia-glcore.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-glcore.so.460.39
	libnvidia-fbc.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-fbc.so.1
	libnvidia-fbc.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-fbc.so
	libnvidia-encode.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-encode.so.1
	libnvidia-encode.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-encode.so
	libnvidia-eglcore.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-eglcore.so.460.39
	libnvidia-container.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-container.so.1
	libnvidia-compiler.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-compiler.so.460.39
	libnvidia-cfg.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-cfg.so.1
	libnvidia-cfg.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-cfg.so
	libnvidia-cbl.so.460.39 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-cbl.so.460.39
	libnvidia-allocator.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-allocator.so.1
	libnvidia-allocator.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvidia-allocator.so
	libnvcuvid.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvcuvid.so.1
	libnvcuvid.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libnvcuvid.so
	libicudata.so.66 (libc6,x86-64) => /lib/x86_64-linux-gnu/libicudata.so.66
	libcurl.so.4 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcurl.so.4
	libcurl-gnutls.so.4 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcurl-gnutls.so.4
	libcups.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcups.so.2
	libcuda.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /lib/x86_64-linux-gnu/libcuda.so
	libGLX_nvidia.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLX_nvidia.so.0
	libGLESv2_nvidia.so.2 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2
	libGLESv1_CM_nvidia.so.1 (libc6,x86-64) => /lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1
	libEGL_nvidia.so.0 (libc6,x86-64) => /lib/x86_64-linux-gnu/libEGL_nvidia.so.0
###NV### Thu Feb 11 11:36:51 UTC 2021 #### Notebooks directory: /home/ubuntu/data-science-stack-2.8.0-dev
###NV### Thu Feb 11 11:36:51 UTC 2021 #### Conda detected (0 means not installed): 0
###NV### Thu Feb 11 11:36:51 UTC 2021 #### Target Conda root: /home/ubuntu/conda
###NV### Thu Feb 11 11:36:51 UTC 2021 #### END Diagnostics
```

**Comment by mattf** [comment]
Ubuntu 18.04
```
$ ./data-science-stack setup-system
...
$ reboot
$ ./data-science-stack diagnostics
###NV### Thu Feb 11 11:36:57 UTC 2021 #### START Diagnostics
###NV### Thu Feb 11 11:36:57 UTC 2021 #### Run as: ubuntu
###NV### Thu Feb 11 11:36:57 UTC 2021 #### WSL: false
###NV### Thu Feb 11 11:36:57 UTC 2021 #### OS Flavor: ubuntu
###NV### Thu Feb 11 11:36:57 UTC 2021 #### OS Release: 18.04
###NV### Thu Feb 11 11:36:57 UTC 2021 #### lsb_release:
Description:	Ubuntu 18.04.5 LTS
Release:	18.04
###NV### Thu Feb 11 11:36:57 UTC 2021 #### uname -a
Linux ip-172-31-47-58 5.4.0-1037-aws #39~18.04.1-Ubuntu SMP Fri Jan 15 02:48:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
###NV### Thu Feb 11 11:36:57 UTC 2021 #### Storage (non-tmpfs, non-loopback)
Filesystem      Size  Used Avail Use% Mounted on
udev            7.7G     0  7.7G   0% /dev
/dev/nvme0n1p1   41G  3.1G   38G   8% /
###NV### Thu Feb 11 11:36:57 UTC 2021 #### Network test
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
64 bytes from 8.8.8.8: icmp_seq=1 ttl=110 time=1.34 ms

--- 8.8.8.8 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1.341/1.341/1.341/0.000 ms
###NV### Thu Feb 11 11:36:57 UTC 2021 #### Driver detected (0 means not installed): 460.39
###NV### Thu Feb 11 11:36:57 UTC 2021 #### NVIDIA SMI:
Thu Feb 11 11:36:58 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.39       Driver Version: 460.39       CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   64C    P0    30W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|  No running processes found                                                 |
+-----------------------------------------------------------------------------+
###NV### Thu Feb 11 11:36:58 UTC 2021 #### CUDA detected (0 means not installed): 0
###NV### Thu Feb 11 11:36:58 UTC 2021 #### Docker detected (0 means not installed): 0
###NV### Thu Feb 11 11:36:58 UTC 2021 #### Shared libraries:
	libnvoptix.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvoptix.so.1
	libnvidia-tls.so.460.39 (libc6,x86-64, OS ABI: Linux 2.3.99) => /usr/lib/x86_64-linux-gnu/libnvidia-tls.so.460.39
	libnvidia-rtcore.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-rtcore.so.460.39
	libnvidia-ptxjitcompiler.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so.1
	libnvidia-ptxjitcompiler.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ptxjitcompiler.so
	libnvidia-opticalflow.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so.1
	libnvidia-opticalflow.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opticalflow.so
	libnvidia-opencl.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-opencl.so.1
	libnvidia-ngx.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ngx.so.1
	libnvidia-ml.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so.1
	libnvidia-ml.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ml.so
	libnvidia-ifr.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so.1
	libnvidia-ifr.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-ifr.so
	libnvidia-gtk3.so.440.82 (libc6,x86-64) => /usr/lib/libnvidia-gtk3.so.440.82
	libnvidia-gtk2.so.440.82 (libc6,x86-64) => /usr/lib/libnvidia-gtk2.so.440.82
	libnvidia-glvkspirv.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glvkspirv.so.460.39
	libnvidia-glsi.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glsi.so.460.39
	libnvidia-glcore.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-glcore.so.460.39
	libnvidia-fbc.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so.1
	libnvidia-fbc.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-fbc.so
	libnvidia-encode.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-encode.so.1
	libnvidia-encode.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-encode.so
	libnvidia-eglcore.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-eglcore.so.460.39
	libnvidia-container.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-container.so.1
	libnvidia-compiler.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-compiler.so.460.39
	libnvidia-cfg.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so.1
	libnvidia-cfg.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-cfg.so
	libnvidia-cbl.so.460.39 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-cbl.so.460.39
	libnvidia-allocator.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so.1
	libnvidia-allocator.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvidia-allocator.so
	libnvcuvid.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so.1
	libnvcuvid.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libnvcuvid.so
	libicudata.so.60 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libicudata.so.60
	libcurl.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl.so.4
	libcurl-gnutls.so.4 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcurl-gnutls.so.4
	libcups.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcups.so.2
	libcuda.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so.1
	libcuda.so (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libcuda.so
	libGLX_nvidia.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLX_nvidia.so.0
	libGLESv2_nvidia.so.2 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLESv2_nvidia.so.2
	libGLESv1_CM_nvidia.so.1 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libGLESv1_CM_nvidia.so.1
	libEGL_nvidia.so.0 (libc6,x86-64) => /usr/lib/x86_64-linux-gnu/libEGL_nvidia.so.0
###NV### Thu Feb 11 11:36:58 UTC 2021 #### Notebooks directory: /home/ubuntu/data-science-stack-2.8.0-dev
###NV### Thu Feb 11 11:36:58 UTC 2021 #### Conda detected (0 means not installed): 0
###NV### Thu Feb 11 11:36:58 UTC 2021 #### Target Conda root: /home/ubuntu/conda
###NV### Thu Feb 11 11:36:58 UTC 2021 #### END Diagnostics
```
```

**Comment by mattf** [comment]
@bmwshop ptal

**Comment by bmwshop** [comment]
thank you!

**Pull request merged**
